POST http://localhost:3001/api/torneo-abierto/unirse/10A0A8C01 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYzlmMDljNTlmYmJlZTMyMzZjODdjNSIsImVtYWlsIjoibWFzaXBkYXJpb0BnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImRhcmlvbWFzaXAiLCJpYXQiOjE2NTkwOTE4NjJ9.QfktSvPV21rFl09y4k5zcYvu7zpQ5oprVJE57Xu4kMQ